version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./stream:/stream
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"