server:
  port: 8081
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: httptrace

pulsar:
  producer:
    url: pulsar://localhost:6650
    topic: json-changes
    producer-name: changes-sender