server:
  port: 8081
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: httptrace

pulsar:
  producer:
    url: pulsar://localhost:6650

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false


  liquibase:
    change-log: classpath:db/changelog.yml